### ISSUE TITLE
script `make-db-cover.py` returns `ValueError: cannot set .minhash on FrozenSourmashSignature`

### ISSUE THREAD

**Issue by taylorreiter** [dib-lab/2022-database-covers#1]
sourmash version 4.6.1 

```
./scripts/make-db-cover.py genbank-2022.03-fungi-k31.zip -o genbank-2022.03-fungi-k31-scaled1k-cover.zip --scaled 1000
```

returns:
```
examining GCA_022578855.1 Nemania serpen... from genbank-2022.03-fungi-k31.zip - #0, 0 total hashes.
saving original (downsampled?) signature.
Traceback (most recent call last):
  File "/home/ubuntu/build-cover-dbs/./scripts/make-db-cover.py", line 60, in <module>
    sys.exit(main())
  File "/home/ubuntu/build-cover-dbs/./scripts/make-db-cover.py", line 45, in main
    ss.minhash = mh
  File "/home/ubuntu/build-cover-dbs/.snakemake/conda/33c5e84b9f0989a91e7cf61f0317eae0_/lib/python3.10/site-packages/sourmash/signature.py",
 line 260, in minhash
    raise ValueError("cannot set .minhash on FrozenSourmashSignature")
ValueError: cannot set .minhash on FrozenSourmashSignature
```

**Comment by ctb** [comment]
Add a `ss = ss.to_mutable()` the line before line 45 and give that a try!

**Comment by taylorreiter** [comment]
```
examining GCA_022636895.1 Escherichia co... from genbank-2022.03-bacteria-k51.zip - #4, 1592 total hashes.
Traceback (most recent call last):
  File "/home/ubuntu/build-cover-dbs/./scripts/make-db-cover.py", line 61, in <module>
    sys.exit(main())
  File "/home/ubuntu/build-cover-dbs/./scripts/make-db-cover.py", line 54, in main
    ss.minhash = new_mh
  File "/home/ubuntu/build-cover-dbs/.snakemake/conda/33c5e84b9f0989a91e7cf61f0317eae0_/lib/python3.10/site-packages/sourmash/signature.py", line 260, in minhash
    raise ValueError("cannot set .minhash on FrozenSourmashSignature")
ValueError: cannot set .minhash on FrozenSourmashSignature
```

but then adding `ss = ss.to_mutable()` before line 54 too made it work! thank you!
